services:
  trainer:
    image: unsloth/unsloth:latest
    container_name: unsloth_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./:/workspace
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --ServerApp.token='' --IdentityProvider.token='' --notebook-dir=/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  inference:
    build:
      context: .
      dockerfile: Dockerfile.vllm
    container_name: vllm_inference
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HF_HOME=/workspace/models/cache
      - VLLM_USE_V1=1
      - TOKENIZERS_PARALLELISM="true"
    volumes:
      - ./:/workspace
    ports:
      - "8889:8888"
    shm_size: '8gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
